/* eslint-disable */
// prettier-ignore
//@ts-ignore
// import { default as packageJson } from "../../package.json";

const AUTOGENERATED_COMMENT = `
//@ts-nocheck
/* eslint-disable */
/**
* 该文件为自动生成，尽量别修改
*
* @version ${6}
*/
`;

const SERVICE_BEGINNING = `${AUTOGENERATED_COMMENT}
import * as request from '@/request';
import type { FetchOptions, AxiosRequestConfig } from "@cyberutopian/request";

export type SwaggerResponse<R> = R;
`;
const SERVICE_NEEDED_FUNCTIONS = `
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const __DEV__ = process.env.NODE_ENV !== "production";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function overrideConfig(
  config?: AxiosRequestConfig,
  configOverride?: AxiosRequestConfig,
): AxiosRequestConfig {
  return {
    ...config,
    ...configOverride,
    headers: {
      ...config?.headers,
      ...configOverride?.headers,
    },
  };
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function template(path: string, obj: { [x: string]: any } = {}) {
    Object.keys(obj).forEach((key) => {
      const re = new RegExp(\`{\${key}}\`, "i");
      path = path.replace(re, obj[key]);
    });

    return path;
}

function isFormData(obj: any) {
  // This checks for the append method which should exist on FormData instances
  return (
    (typeof obj === "object" &&
      typeof obj.append === "function" &&
      obj[Symbol.toStringTag] === undefined) ||
    obj[Symbol.toStringTag] === "FormData"
  );
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function objToForm(requestBody: object) {
  if (isFormData(requestBody)) {
    return requestBody;
  }
  const formData = new FormData();

  Object.entries(requestBody).forEach(([key, value]) => {
    value && formData.append(key, value);
  });

  return formData;
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
`;

const DEPRECATED_WARM_MESSAGE = 'This endpoint deprecated and will be remove. Please use an alternative';

export { AUTOGENERATED_COMMENT, DEPRECATED_WARM_MESSAGE, SERVICE_BEGINNING, SERVICE_NEEDED_FUNCTIONS };
